#include "timer.h"

void TIMER1_Init(void)
{
    TIM1_TimeBaseInit(49, TIM1_COUNTERMODE_UP, 499, 1); //Sample
    TIM1_ITConfig(TIM1_IT_UPDATE, ENABLE);
    TIM1_Cmd(ENABLE);
}

void TIMER2_Init(void)
{
    TIM2_TimeBaseInit(TIM2_PRESCALER_1, 99); //PWM 160khz, Duty 100
    TIM2_OC1Init(TIM2_OCMODE_PWM2, TIM2_OUTPUTSTATE_ENABLE, 100, TIM2_OCPOLARITY_LOW);
    TIM2_OC3Init(TIM2_OCMODE_PWM2, TIM2_OUTPUTSTATE_ENABLE, 0, TIM2_OCPOLARITY_LOW);
    TIM2_OC1PreloadConfig(ENABLE);
    TIM2_OC3PreloadConfig(ENABLE);
    TIM2_ARRPreloadConfig(ENABLE);
    TIM2_Cmd(ENABLE);
}

void TIMER4_Init(void)
{
    TIM4_TimeBaseInit(TIM4_PRESCALER_128, 124);//Timer 1ms
    TIM4_ITConfig(TIM4_IT_UPDATE, ENABLE);
    TIM4_Cmd(ENABLE);
}

